default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: sfl_development
  host: "0.0.0.0"

test:
  <<: *default
  database: sfl_test
  host: "0.0.0.0"

production:
  <<: *default
  database: sfl_production
