ScoringCriterion.create([
  { name: "1st Team Immunity", points: 3 },
  { name: "2nd Team Immunity", points: 2 },
  { name: "1st Team Reward", points: 2 },
  { name: "2nd Team Reward", points: 1 },
  { name: "Won Individual Immunity", points: 5 },
  { name: "Won Individual Reward", points: 3 },
  { name: "Joined Individual Reward", points: 1 },
  { name: "Found Immunity Idol", points: 5 },
  { name: "Found Immunity Idol Clue", points: 2 },
  { name: "Received a Vote", points: -1 },
  { name: "Voted Off", points: -2 },
  { name: "Medical Evac/Pulled", points: -2 },
  { name: "Quit", points: -3 },
  { name: "Reached Merge", points: 2 },
  { name: "Reached Final 3", points: 5 },
  { name: "Won Survivor", points: 12 },
])

Episode.create([
  { number: 1, title: "Can You Reverse the Curse?" },
  { number: 2 },
  { number: 3 },
])

Castaway.create([
  { first_name: "Domenick", last_name: "Abbate", headshot_filename: "domenick_abbate.jpg" },
  { first_name: "Desiree", last_name: "Afuye", headshot_filename: "desiree_afuye.jpg" },
  { first_name: "Kellyn", last_name: "Bechtold", headshot_filename: "kellyn_bechtold.jpg" },
  { first_name: "Jenna", last_name: "Bowman", headshot_filename: "jenna_bowman.jpg" },
  { first_name: "Jacob", last_name: "Derwin", headshot_filename: "jacob_derwin.jpg" },
  { first_name: "Stephanie", last_name: "Gonzalez", headshot_filename: "stephanie_gonzalez.jpg" },
  { first_name: "Wendell", last_name: "Holland", headshot_filename: "wendell_holland.jpg" },
  { first_name: "Donathan", last_name: "Hurley", headshot_filename: "donathan_hurley.jpg" },
  { first_name: "Laurel", last_name: "Johnson", headshot_filename: "laurel_johnson.jpg" },
  { first_name: "Stephanie", last_name: "Johnson", headshot_filename: "stephanie_johnson.jpg" },
  { first_name: "Bradley", last_name: "Kleihege", headshot_filename: "bradley_kleihege.jpg" },
  { first_name: "James", last_name: "Lim", headshot_filename: "james_lim.jpg" },
  { first_name: "Chris", last_name: "Noble", headshot_filename: "chris_noble.jpg" },
  { first_name: "Sebastian", last_name: "Noel", headshot_filename: "sebastian_noel.jpg" },
  { first_name: "Angela", last_name: "Perkins", headshot_filename: "angela_perkins.jpg" },
  { first_name: "Morgan", last_name: "Ricke", headshot_filename: "morgan_ricke.jpg" },
  { first_name: "Brendan", last_name: "Shapiro", headshot_filename: "brendan_shapiro.jpg" },
  { first_name: "Chelsea", last_name: "Townsend", headshot_filename: "chelsea_townsend.jpg" },
  { first_name: "Libby", last_name: "Vincek", headshot_filename: "libby_vincek.jpg" },
  { first_name: "Michael", last_name: "Yerger", headshot_filename: "michael_yerger.jpg" },
])
